[package]
name = "todo-app-application"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.56"
serde = { version = "1.0.137", features = ["derive"] }
thiserror = "1.0.31"
todo-app-domain = { path = "../todo-app-domain" }

[dev-dependencies]
