services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    user: postgres
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgres/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  postgres-data:
